# Generated by Django 4.1.1 on 2024-05-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='user',
        ),
    ]
