# Generated by Django 4.1.1 on 2024-05-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Женат(замужем)'), ('single', 'Холост(не замужем)'), ('searching', 'В активном поиске')], max_length=20, null=True, verbose_name='Семейное положение'),
        ),
    ]
