# Generated by Django 4.1.1 on 2024-05-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'В браке'), ('single', 'Все сложно'), ('searching', 'В активном поиске')], default='searching', max_length=20, null=True, verbose_name='Семейное положение'),
        ),
    ]
