name: Main Core workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Пока я думаю, не мешай тупица!"

      - name: Checkout code  # Название шага: Получение кода из репозитория
        uses: actions/checkout@v2  # Использование действия для получения кода
        

      - name: SSH into remote server   # Название шага: Подключение к удаленному серверу по SSH и перезапуск контейнеров
        uses: appleboy/ssh-action@master  # Использование действия для работы с SSH
        with:
          host: ${{ secrets.REMOTE_HOST }}  # Переменная для хоста удаленного сервера
          username: ${{ secrets.REMOTE_USERNAME }}  # Переменная для имени пользователя SSH
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Переменная для приватного ключа SSH
          script: |   
            cd /root/django-social/
           
            
            git pull origin main

            

            cd /root/django-social/core/            
            source /root/django-social/venv/bin/activate        
            pip install -r /root/django-social/requirements.txt
            python3 manage.py makemigrations
            python3 manage.py migrate
            python3 manage.py collectstatic --noinput
            redis-server 
            sleep 10
            gunicorn core.wsgi:application --bind 127.0.0.1:8000 --daemon
            
            daphne -b 127.0.0.1 -p 8000 core.asgi:application
           
            service nginx restart
            
            

  send_message:
    runs-on: ubuntu-latest
    needs: print-message
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          
          message: Деплой успешно выполнен!
