name: Main Core Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  deploy:
    name: Deploy and Restart Server
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Пока я думаю, не мешай тупица!"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/django-social/core/

            pkill -f gunicorn  # Завершаем процессы Gunicorn
            pkill -f "python3 manage.py runserver"  # Завершаем процессы runserver
            sleep 10  # Ожидание перед перезапуском

            git pull origin main  # Обновляем код из репозитория

            source /root/django-social/venv/bin/activate

            pip install -r /root/django-social/requirements.txt
            python3 manage.py makemigrations
            python3 manage.py migrate
            python3 manage.py collectstatic --noinput
            redis-server &  # Запускаем Redis
            gunicorn -w 4 -b 127.0.0.1:8000 core.wsgi:application &  # Запускаем Gunicorn
            daphne -b http://127.0.0.1 -p 8000 core.asgi:application  # Запускаем Daphne


      - name: Send deployment success message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Деплой успешно выполнен!
